[workspace]
authors = [
    "Stephane Rigaud <stephane.rigaud@imba.oeaw.ac.at>", 
    "Gaelle Letort <gaelle.letort@pasteur.fr>","Julie Mabon <julie.mabon@pasteur.fr>"]
channels = ["conda-forge"]
name = "cellpose-appose"
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]
test = { cmd = "python cp3.py" }

[dependencies]
python = ">=3.10.3,<3.13"

[pypi-dependencies]
# Shared dependencies (available in both envs)
appose = ">=0.10.1, <0.11"

# CellPose 3 feature
[feature.cp3.pypi-dependencies]
cellpose = ">=3, <4"

# CellPose 4 feature  
[feature.cp4.pypi-dependencies]
cellpose = ">=4, <5"

[environments]
default = { features = ["cp3"] } 
cp3 = { features = ["cp3"] }
cp4 = { features = ["cp4"] }
