[workspace]
authors = [
    "Stephane Rigaud <stephane.rigaud@imba.oeaw.ac.at>",
    "Gaelle Letort <gaelle.letort@pasteur.fr>",
    "Julie Mabon <julie.mabon@pasteur.fr>",
]
channels = ["conda-forge"]
name = "cellpose-appose"
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]
version = "0.1.0"

[dependencies]
python = ">=3.10.3,<3.13"
packaging = ">=26.2,<27"

[pypi-dependencies]
appose = ">=0.10.1, <0.12"

# --- Platform-specific PyTorch installation ---
# Rely on the oldest torch version compatible with both 126 and 130 CUDA versions
# Default is GPU with CUDA 12.6, but user can select CPU or others CUDA version in the "Advanced options" of the plugin.
# See for more details on torch versions and CUDA support: https://pytorch.org/get-started/previous-versions/

[target.linux.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cu126" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cu126" }

[target.win.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cu126" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cu126" }

[target.osx-arm64.pypi-dependencies]
torch = { version = ">=2.9, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.24, <0.26", index = "https://download.pytorch.org/whl/cpu" }

# Deprecated: osx-64 support should be drop in favor of osx-arm64
[target.osx-64.pypi-dependencies]
torch = { version = ">=2.2.2, <2.11", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.17.2, <0.26", index = "https://download.pytorch.org/whl/cpu" }

# --- CellPose version features ---
[feature.cp3.pypi-dependencies]
cellpose = ">=3, <4"

[feature.cp4.pypi-dependencies]
cellpose = ">=4, <5"

# --- Environments ---
[environments]
default = { features = ["cp3"] }
cp3 = { features = ["cp3"] }
cp4 = { features = ["cp4"] }
