name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-os:

    strategy:
      fail-fast: true
      matrix:
        name:
          - ubuntu
        include:
          - name: ubuntu
            os: ubuntu-20.04
            c-compiler: gcc
            cxx-compiler: g++
            cmake-build-type: Release
            cmake-build-flag: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: zulu
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install -DskipTests
        shell: bash -l {0}

      - name: Get Maven Version and Upload Artifact
        shell: bash
        run: |
          MVN_VERSION=$(mvn -q \
            -Dexec.executable=echo \
            -Dexec.args='${project.version}' \
            --non-recursive \
            exec:exec)
          MVN_NAME=$(mvn -q \
            -Dexec.executable=echo \
            -Dexec.args='${project.name}' \
            --non-recursive \
            exec:exec)
          echo "version=${MVN_VERSION}" >> $GITHUB_OUTPUT
          echo "name=${MVN_NAME}" >> $GITHUB_OUTPUT
        id: mvn_info

      - name: Upload native library
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-artifact
          path: target/${{steps.mvn_info.outputs.name}}-${{steps.mvn_info.outputs.version}}.jar
